// =================================================
// =                                               =
// = Sound.Autogenerated.cs                        =
// =                                               =
// = AUTO-GENERATED FILE - Do not edit!            =
// =                                               =
// =================================================

using System.Collections.Generic;

namespace Tobo.Audio
{
    public partial class Sound
    {
        public enum ID
        {
            None = 0,
        }


        internal static Dictionary<string, string> FilenameToSoundIDName { get; private set; } = new Dictionary<string, string>()
        {
        };

        internal static Dictionary<string, Sound.ID> SoundIDNameToSoundID { get; private set; } = new Dictionary<string, Sound.ID>()
        {
            { "None", Sound.ID.None },
        };
    }
}

